name: Daily

on:
  schedule:
    - cron: '21 17 * * *'
  pull_request: {} ## hack it

env:
  GOPROXY: https://proxy.golang.org

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      IMG: local/kubegres:scan
      PLATFORMS: linux/amd64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/scan
        with:
          format: 'sarif'
          output: 'trivy-results.sarif'
