name: Publish Release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+-tetrate-v[0-9]+' ]  # v1.16.0-tetrate-v7

env:
  GOPROXY: https://proxy.golang.org

jobs:
  docker-hub-push:
    runs-on: ubuntu-latest
    env:
      IMG: tetrate/kubegres:${{ github.ref_name }}
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - uses: docker/setup-buildx-action@v3
        id: setup-buildx
        with:
          platforms: ${{ env.PLATFORMS }}
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - env:
          DOCKER_BUILDER_NAME: ${{ steps.setup-buildx.outputs.name }}
        run: make docker-build-push
