name: Scan

on:
  push:
    branches:
      - main
      - release-**
    tags: [ 'v[0-9]+.[0-9]+-tetrate-v[0-9]+' ]  # v1.16-tetrate-v7
  pull_request:
    branches:
      - main
      - release-**
  workflow_dispatch: {}

env:
  GOPROXY: https://proxy.golang.org

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/scan
        with:
          format: 'table'
